apiVersion: v1
kind: Secret
metadata:
  name: night-owl-secret
stringData:
  DB_PASSWORD: postgres
  CLOUD_NAME: dectbvmyx
  CLOUD_API_KEY: "442698497359214"
  CLOUD_API_SECRET: qlWVxi7gQVA9LjjoXmw0UiPzabg
  SECRET_KEY: django-insecure-vt&#4&s!80tvp(!3^37u5@m_%=$e)8+k$dgblizxt4(90ji9)&
type: Opaque