image: python:3.10

variables:
  POSTGRES_DB: "night_owl"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  PGDATA: "/var/lib/postgresql/data"
  POSTGRES_INITDB_ARGS: "--encoding: UTF8 --data-checksums"
  DB_HOST: postgres
  DB_NAME: night_owl
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: 5432
  BROKER: redis

services:
  - postgres:latest
  - redis:latest

build-job:
  stage: build
  before_script:
    - python -V
    - pip install -r requirements.txt
    - echo "Setup completed"
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - python manage.py makemigrations
    - python manage.py migrate

test-job1:
  stage: test
  script:
    - coverage run --source="." manage.py test --parallel
    - coverage json

deploy-staging:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: staging