image: python:3.10
services:
  - name: postgres
    alias: postgres
  - name: redis:latest
    alias: redis

cache:
  paths:
    - .cache/pip

variables:
  POSTGRES_DB: "night_owl"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST_AUTH_METHOD: trust
  PGDATA: "/var/lib/postgresql/data"
  DB_HOST: postgres
  DB_NAME: night_owl
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: 5432
  BROKER: redis
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


before_script:
  - python -V
  - apt-get update && apt-get install -y -q --no-install-recommends build-essential libpq-dev
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - echo "Setup completed"


test:
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - python manage.py test --parallel

deploy:
  script:
    - echo "Run staging"
    - python manage.py runserver 0.0.0.0:8089
    - echo "Run successful"