# Generated by Django 4.1 on 2022-11-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cartdetail_category_option_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
