# Generated by Django 4.1 on 2022-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_order_note'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('sold_amount__gte', 0)), name='sold_amount_positive'),
        ),
    ]
