# Generated by Django 4.1 on 2022-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_type_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='night_owl/product'),
        ),
    ]
