# Generated by Django 4.1 on 2022-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_sold_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_shipping_fee__gte', 0)), name='positive_total_shipping_fee'),
        ),
    ]
