# Generated by Django 4.1 on 2022-12-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_order_positive_total_shipping_fee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='voucher_end_date_gte_start_date_constraint'),
        ),
    ]
