# Generated by Django 4.1 on 2022-12-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_voucher_voucher_end_date_gte_start_date_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
