# Generated by Django 4.1 on 2022-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_orderdetail_unit_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rate_range_constraint',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 1), ('rate__lte', 5)), name='rate_range_constraint'),
        ),
    ]
