# Generated by Django 4.1 on 2022-12-22 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_voucher_percentage_voucher_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
