# Generated by Django 4.1 on 2023-01-04 02:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_user_options_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='Product Descriptions'),
        ),
    ]
