# Generated by Django 4.1 on 2023-01-04 02:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='<h1>Product Descriptions<h1>'),
        ),
    ]
