# Generated by Django 4.1 on 2023-03-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voucher_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.voucher'),
        ),
    ]
