apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: redis
spec:
  storageClassName: minikube-redis-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi