apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-initdb-config
data:
  initdb.sql: |
    CREATE USER huy WITH PASSWORD '0937461321Huy@';
    CREATE DATABASE night_owl;
    GRANT ALL ON SCHEMA public TO huy;
    GRANT ALL PRIVILEGES ON DATABASE night_owl TO huy;