apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: postgres